#ifndef GET_PARAMETER_BYTE_RES_HPP
#define GET_PARAMETER_BYTE_RES_HPP

#ifndef START_BYTE_INDEX_OFFSET_FROM_MAIN_SERVICE
#define START_BYTE_INDEX_OFFSET_FROM_MAIN_SERVICE 2
#endif // !START_BYTE_INDEX_OFFSET_FROM_MAIN_SERVICE

#ifndef NR_OF_BYTES_OFFSET_FROM_MAIN_SERVICE
#define NR_OF_BYTES_OFFSET_FROM_MAIN_SERVICE 4
#endif // !NR_OF_BYTES_OFFSET_FROM_MAIN_SERVICE

#ifndef FIRST_BYTE_OFFSET_FROM_MAIN_SERVICE
#define FIRST_BYTE_OFFSET_FROM_MAIN_SERVICE 6
#endif // !FIRST_BYTE_OFFSET_FROM_MAIN_SERVICE

#ifndef ERROR_CODE_OFFSET_FROM_MAIN_SERVICE
#define ERROR_CODE_OFFSET_FROM_MAIN_SERVICE 6
#endif // !ERROR_CODE_OFFSET_FROM_MAIN_SERVICE

#include "../Utility/GetErrorDescription.hpp"
#include "../../Utility/Macros.hpp"

bool decodeGetParameterByteRes(unsigned char* telegramCharArray, unsigned int telegramLength);

#endif // GET_PARAMETER_BYTE_RES_HPP